# Jekyll configuration

name: backbone.hateoas
description: backbone.hateoas

# url is currently only used only for the RSS feed in feed.xml
url: http://gomoob.github.io/backbone.hateoas

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: /backbone.hateoas

# This can be '' to hide the Github nav button
github: 'gomoob/backbone.hateoas'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: true

permalink: /:year/:month/:title
paginate: 5
paginate_path: "news/page:num/"

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
